# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from simlab.simulation.proto import algorithm_backend_pb2 as simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in simlab/simulation/proto/algorithm_backend_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AlgorithmSimulationBackendStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/simlab.algorithm.v1.AlgorithmSimulationBackend/CreateSession',
                request_serializer=simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/simlab.algorithm.v1.AlgorithmSimulationBackend/Reset',
                request_serializer=simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.ResetRequest.SerializeToString,
                response_deserializer=simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.StateResponse.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/simlab.algorithm.v1.AlgorithmSimulationBackend/Step',
                request_serializer=simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.StepRequest.SerializeToString,
                response_deserializer=simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.StateResponse.FromString,
                _registered_method=True)
        self.Close = channel.unary_unary(
                '/simlab.algorithm.v1.AlgorithmSimulationBackend/Close',
                request_serializer=simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.CloseRequest.SerializeToString,
                response_deserializer=simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.CloseResponse.FromString,
                _registered_method=True)


class AlgorithmSimulationBackendServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlgorithmSimulationBackendServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.CreateSessionRequest.FromString,
                    response_serializer=simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.CreateSessionResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.ResetRequest.FromString,
                    response_serializer=simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.StateResponse.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.StepRequest.FromString,
                    response_serializer=simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.StateResponse.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.CloseRequest.FromString,
                    response_serializer=simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.CloseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simlab.algorithm.v1.AlgorithmSimulationBackend', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simlab.algorithm.v1.AlgorithmSimulationBackend', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AlgorithmSimulationBackend:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simlab.algorithm.v1.AlgorithmSimulationBackend/CreateSession',
            simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.CreateSessionRequest.SerializeToString,
            simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simlab.algorithm.v1.AlgorithmSimulationBackend/Reset',
            simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.ResetRequest.SerializeToString,
            simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.StateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simlab.algorithm.v1.AlgorithmSimulationBackend/Step',
            simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.StepRequest.SerializeToString,
            simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.StateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simlab.algorithm.v1.AlgorithmSimulationBackend/Close',
            simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.CloseRequest.SerializeToString,
            simlab_dot_simulation_dot_proto_dot_algorithm__backend__pb2.CloseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
